name: Setup Git credentials
description: Action to setup git credentials

inputs:
  token:
    description: Access token
    required: true
  host:
    description: Git host
    required: false
    default: github.com

runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
