name: 'Setup Git credentials'
description: 'Action to setup git credentials'
inputs:
  token:
    description: 'Access token'
    required: true
    default: ''
  host:
    description: 'Git host'
    required: true
    default: 'github.com'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
