name: Check dist

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - '**.md'
      - ".gitignore"

concurrency: ${{ github.ref }}

jobs:
  check-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm i -g @vercel/ncc
          npm ci

      - name: Rebuild dist directory
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            git config --global user.name "SanthoshNath"
            git config --global user.email "hsohtnas001@gmail.com"
            git add dist
            git commit -m "Rebuild dist directory"
            git push origin ${{ github.head_ref }}
          fi
